### PR TITLE
Added switch to allow days value in reverse order

### PR DESCRIPTION
**Pull request by seanmtracey**

### CODE REVIEW

**Comment by radiodario** [comment]
✌️

**Comment by radiodario** [comment]
can we perhaps add a test for this?

**Comment by peter-mouland** [comment]
yeah, a functional test would be good. something like testing the datapoints on the chart (line + column) match the values being sent in i.e. `jan:10` and `feb:20` are plotted on the charts with `10` on `Jan` and `20` on `feb`. (just to make sure the reverse in the code hasn't accidentally switched the output too)

**Comment by seanmtracey** [comment]
Righto, working on it now.

**Pull request merged**
